- name: Ensure rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present

- name: Create shared backup destination
  ansible.builtin.file:
    path: /home/app_backups
    state: directory
    mode: '0755'

- name: Create folder for backup scripts
  ansible.builtin.file:
    path: backups
    state: directory
    mode: '0755'

- name: Create cron backup job (yc)
  ansible.builtin.cron:
    name: "Backup yc"
    hour: "0"
    job: "/home/poduser/backups/backup_yc.sh"

- name: Create cron backup job (df)
  ansible.builtin.cron:
    name: "Backup df"
    hour: "1"
    job: "/home/poduser/backups/backup_df.sh"

- name: Copy backup scripts to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: backups/
    mode: '0644'
  loop:
    - backup_df.sh
    - backup_yc.sh
