---
- name: Add ansible user
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
    
  tasks:

    - ansible.builtin.import_role:
        name: eingram23.linux.add_eingram_user