---
- name: Update software/kernel packages
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  tasks:
  
    - name: Run main tasks
      ansible.builtin.import_role:
        name: eingram23.linux.linux_update
