- ansible.builtin.debug:
    var: script

- name: sh script
  when: script[-2:] == "sh"
  block:
    - name: Run sh script on host
      ansible.builtin.shell: /var/tmp/{{ script }} {{ param }}
      args:
        executable: sh
      register: sh_output
      ignore_errors: true

    - name: Show script output
      ansible.builtin.debug:
        var: sh_output.stdout_lines
      when: sh_output is defined

    - name: Show script error
      ansible.builtin.debug:
        var: sh_output.stderr
      when: sh_output.stderr is defined and sh_output.stderr != ""

- name: Python script
  when: script[-2:] == "py"
  block:
    - name: Run python file on host
      ansible.builtin.shell: /var/tmp/{{ script }} {{ param }}
      args:
        executable: python3
      register: py_output
      ignore_errors: true
      when: script[-3:] == "py"

    - name: Show script output
      ansible.builtin.debug:
        var: py_output.stdout_lines
      when: py_output is defined

    - name: Show script error
      ansible.builtin.debug:
        var: py_output.stderr
      when: py_output.stderr is defined and py_output.stderr != ""
