---
- name: Create in memory inventory
  add_host:
    name: "{{ inmem_item }}.{{ dns_suffix_list[0] }}"
    groups: temp_group
    ansible_user: "{{ inmem_user | default('ansible')}}"
    ansible_become_user: "{{ inmem_user | default('root')}}"
    ansible_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
  loop: "{{ vm_name_list }}"
  loop_control:
    loop_var: inmem_item
