---
- name: Check for updates using yum
  ansible.builtin.yum:
    list: updates
    update_cache: true
  register: yumoutput
  when: ansible_distribution == 'Rocky' or
        ansible_distribution == 'Red Hat Enterprise Linux'

- name: Output list of updates
  ansible.builtin.debug:
    msg: "{{ yumoutput | json_query('results[].{name: name, release: release, version: version}') }}"

# - ansible.builtin.debug:
#     var: yumoutput