---
- name: Install dnf-utils (if needed)
  ansible.builtin.package:
    name: dnf-utils

- name: Update repo info and update installed packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true

- name: Check if reboot needed
  ansible.builtin.include_tasks:
    file: checkreboot.yaml

- name: Reboot host
  ansible.builtin.reboot:
  when: reboot_required_rhel.rc != 0 and
        reboot == "yes"

- name: Remove unused kernels
  shell: dnf remove --oldinstallonly -y
  when: reboot_required_rhel.rc != 0 and
        reboot == "yes"