---
- name: Install yum-utils (if needed)
  ansible.builtin.package:
    name: yum-utils

- name: Update repo info and update installed packages
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true

- name: Remove unneeded packages
  ansible.builtin.yum:
    autoremove: true

- name: Check if reboot needed
  ansible.builtin.include_tasks:
    file: checkreboot.yaml

- name: Reboot host
  ansible.builtin.reboot:
  when: reboot_required_centos.rc != 0 and
        reboot == "yes"

- name: Remove unused kernels
  ansible.builtin.shell: package-cleanup --oldkernels -y
  when: reboot_required_centos.rc != 0 and
        reboot == "yes"
