---
- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Enable firewall rules for nfs
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - nfs
    - nfs3
    - mountd
    - rpc-bind
  notify: Restart firewalld

- name: Install nfs and rpcbind services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nfs-server
    - rpcbind

- name: Add exports
  ansible.builtin.copy:
    src: exports
    dest: /etc
    mode: '0644'
    backup: true
  notify: Reload nfs