---
- name: Install zfs-release to match kernel
  ansible.builtin.shell: |
    dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm

- name: Instal epel-release and usbutils
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: present
  loop:
    - epel-release
    - usbutils
  loop_control:
    loop_var: package

- name: Run SuperMicro specific tasks
  when: ansible_product_name == "X9SCL/X9SCM"
  block:
    - name: Install SuperMicro packages
      ansible.builtin.dnf:
        name: "{{ sm_package }}"
        state: present
      loop:
        - pci-utils
        - kmod-mpt3sas
        - elrepo-release
      loop_control:
        loop_var: sm_package

    - name: Enable mpt3sas module
      community.general.modprobe:
        name: mpt3sas
        state: present

  ansible.builtin.dnf:
    name: "{{ sm_package }}"
    state: present
  loop:
    - pci-utils
    - kmod-mpt3sas
    - elrepo-release
  loop_control:
    loop_var: sm_package

- name: Disable ZFS repo, enable ZFS-KMOD and install ZFS
  ansible.builtin.dnf:
    disablerepo:
      - zfs
    enablerepo:
      - zfs-kmod
    name: zfs
    state: present

- name: Enable ZFS module
  community.general.modprobe:
    name: zfs
    state: present

- name: Force load of zfs module by systemd
  ansible.builtin.copy:
    src: zfs.conf
    dest: /etc/modules-conf.d
    mode: '0644'

- name: Create zfs systemd override folder
  ansible.builtin.file:
    path: /etc/modules/conf.d/zfs-import-cache-service.d
    state: directory
    mode: '0751'

- name: Copy zfs override file
  ansible.builtin.copy:
    src: zfs-override.conf
    dest: /etc/modules/conf.d/zfs-import-cache-service.d/override.conf

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload zfs
  ansible.builtin.systemd:
    name: zfs-import-cache
    state: restarted
