---
- name: Install firewalld if needed
  ansible.builtin.package: 
    name: firewalld
    state: present

- name: start firewalld
  ansible.builtin.service: 
    name: firewalld
    state: started
    enabled: true

- name: Create firewall rules
  ansible.posix.firewalld:
    port: "{{ fw_port_item }}"
    zone: public
    permanent: true
    state: enabled
  loop: "{{ fw_port }}"
  loop_control:
    loop_var: fw_port_item
  # notify:
  #   - Restart firewall

- name: Restart firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
