---
- name: Install rocky/rhel packages
  when: ansible_facts['distribution'] in ['Rocky', 'RedHat']
  ansible.builtin.package:
    name: "{{ core_pkg_item_rocky_rhel }}"
    state: present
  loop: "{{ rocky_rhel_packages }}"
  loop_control:
    loop_var: core_pkg_item_rocky_rhel

- name: Install ubuntu packages
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.package:
    name: "{{ core_pkg_item_ubuntu }}"
    state: present
  loop: "{{ ubuntu_packages }}"
  loop_control:
    loop_var: core_pkg_item_ubuntu

- name: Perform RHEL specific tasks
  when: ansible_facts['distribution'] == 'RedHat'
  block:
    - name: Update subscription manager
      ansible.builtin.shell: subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms
