---
- name: Install extra packages
  ansible.builtin.package:
    name: "{{ core_pkg_item }}"
    state: installed
  loop:
    - python3
    - yum-utils
    - zip
    - git
    - bind-utils
  loop_control:
    loop_var: core_pkg_item

- name: Install pip (rhel/rocky9)
  ansible.builtin.package:
    name: pip
    state: installed
  when: ansible_facts['distribution_major_version'] == '9'

- block:
    - name: Enable powertools on rocky
      ansible.builtin.shell: dnf config-manager --set-enabled powertools
      when: ansible_facts['distribution_major_version'] == '8'

    - name: Install rocky packages
      ansible.builtin.dnf:
        name: "{{ core_pkg_item_rocky }}"
        state: present
      loop:
        - epel-release
        - htop
        - iotop
      loop_control:
        loop_var: core_pkg_item_rocky
  when: ansible_facts['distribution'] == 'Rocky'

- block:
    - name: Update subscription manager
      ansible.builtin.shell: subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms

    - name: Install rhel packages
      ansible.builtin.dnf:
        name: "{{ core_pkg_item_rhel }}"
        state: present
      loop:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - htop
      loop_control:
        loop_var: core_pkg_item_rhel
  when: ansible_facts['distribution'] == 'RedHat'
