---
- name: Check if {{ user_account }} exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ user_account }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Create user - {{ user_account }}
  when: user_check.ansible_facts.getent_passwd is not defined or not user_check.ansible_facts.getent_passwd
  ansible.builtin.user:
    name: "{{ user_account }}"
    password: "{{ user_password | password_hash('sha512') }}"
  no_log: true

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set admin user
  when: admin_user == "yes"
  block:
    - name: Add sudoers users to wheel group
      ansible.builtin.user:
        name: "{{ user_account }}"
        groups: wheel
        append: true
        state: present
        createhome: true

    - name: Set up authorized keys for the deployer user
      when: user_account == "ansible" or user_account == "eingram"
      ansible.posix.authorized_key:
        user: "{{ user_account }}"
        key: "{{ key_item }}"
        state: present
      with_file:
        - id_rsa.pub
      loop_control:
        loop_var: key_item
