---
- name: Install SNMP Windows feature
  ansible.windows.win_feature:
    name: SNMP-Service
    state: present

- name: Enable snmp service
  ansible.windows.win_service:
    name: SNMP
    start_mode: auto
    state: started

- name: Configure snmp settings
  community.windows.win_snmp:
    community_strings:
      - public
    permitted_managers:
      - librenms.local.lan
    action: set

- name: Allow 161 udp through firewall
  ansible.builtin.include_role:
    name: eingram23.windows.win_firewall
  vars:
    rule_name: "SNMP UDP"
    fw_port: "161"
    protocol: "udp"
