---
- name: Install nginx proxy
  hosts: "{{ hostvar }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.linux.nginx_proxy