---
- name: System upgrade
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  strategy: free

  tasks:

    - name: Include linux_update role
      ansible.builtin.include_role:
        name: eingram23.linux.linux_update
        tasks_from: "{{ ansible_facts['os_family'] | lower }}.yaml"
