---
- name: Setup new linux server for Homelab environment
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  tasks:

    - name: Add linux user
      ansible.builtin.include_role:
        name: eingram23.linux.user_mgmt
        tasks_from: add_user
      vars:
        user_id: "{{ user_item }}"
        user_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/ansible:ssh_password') }}"
        admin_user: "yes"
      loop:
        - ansible
        - eingram
      loop_control:
        loop_var: user_item

    - name: Set up chrony
      ansible.builtin.include_role:
        name: eingram23.linux.chrony

    - name: Install core packages
      ansible.builtin.include_role:
        name: eingram23.linux.install_core_pkgs

    - name: Install root certificate into trusted store
      ansible.builtin.include_role:
        name: eingram23.linux.certificates

    - name: Run additional tasks
      when: task is defined
      block:
        - name: Install container engine
          ansible.builtin.include_role:
            name: eingram23.linux.container_host
          when: "'container_host' in task"

        - name: Setup zfs
          ansible.builtin.include_role:
            name: eingram23.linux.filesystem
            tasks_from: zfs
          when: "'zfs' in task"

        - name: Setup nfs
          ansible.builtin.include_role:
            name: eingram23.linux.filesystem
            tasks_from: nfs
          when: "'nfs' in task"

        - name: Setup samba
          ansible.builtin.include_role:
            name: eingram23.linux.filesystem
            tasks_from: samba
          when: "'samba' in task"
